name: Add Checksum to JSON

on:
  pull_request:
    paths:
      - 'index/**/*.json'  # Trigger for any JSON file within the 'index' folder

jobs:
  update-checksum:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install Python dependencies
      run: pip install requests

    - name: Get All Changed Files
      id: files
      uses: jitterbit/get-changed-files@v1

    - name: Run Python Script to Process JSON Files
      run: |
        for file in ${{ steps.files.outputs.all }}; do
          if [[ $file == index/*.json ]]; then
            echo "Processing $file"
            python add_checksum.py $file
          fi
        done

    - name: Commit and Push Changes
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git add .
        git commit -m "Add checksum to JSON" || echo "No changes to commit"
        git push
